version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html

networks:
  default:
    driver: bridge